### ISSUE TITLE
注册酷办公时发送短信接口没有做防刷

### ISSUE THREAD

**Issue by RunnerLee** [SeekArt/IBOS#2]
可以无限次调用，可能被用来短信轰炸，建议对单个号码设置最大发送频率

**Comment by SeekArt** [comment]
目前每个号码一天最多接收10个验证码，不过建议很好，我们应该设置针对单IP发起的验证码请求三次后需要输入验证码

**Comment by RunnerLee** [comment]
指的并不是 IBOS 中的，而是最终调用发送验证码的那个 API。
我试了一下是可以发到 14 条的，就没有接着发下去。

建议接口是针对 `手机号` 做策略，因为针对 IP 只要随便找个 HTTP 代理就能绕过了，例如：
- 单个号码周期内最多发送条数
- 单个号码两次发送最小间隔时间

另外，看了一下 IBOS 的验证短信验证码的代码，对于用户填入的短信验证码，前端只是校验了小于四位并没有考虑大于四位，后端则完全没验证就请求了验证的 API，虽然对于以后修改验证码规则方便，但也会增加一定的压力，建议修改下。

**Comment by icy2003** [comment]
@RunnerLee ip还是手机号的已经反馈，验证的话，其实并不怎么大压力，所以没有做校验

**Comment by irying** [comment]
@RunnerLee 厉害了我的哥，防刷的建议真不错，上个月已经搞定了

**Comment by RunnerLee** [comment]
@irying 那个接口好像开了 debug

**Comment by heiye1024** [comment]
可以弄个ldap功能吗
